### ISSUE TITLE
add gateway.cfg

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#7] opened 2020-11-01 19:16 UTC
This is the original configfile from bitbucket. Just add this to the  ``app-conf`` volume and IMAP will be  available

```
# See the kopano-gateway.cfg(5) manpage for details and more directives.

# Space-separated list of address:port specifiers with optional %interface
# infix for where the server should listen for connections.
# imaps is normally on 993, pop3s on 995.
#
#pop3_listen = *%lo:110
#pop3s_listen =
imap_listen = 0.0.0.0:143
#imaps_listen = 0.0.0.0:993
# File with RSA key for SSL
#ssl_private_key_file = /etc/kopano/gateway/privkey.pem
#File with certificate for SSL
#ssl_certificate_file = /etc/kopano/gateway/cert.pem

# Disable all plaintext authentications unless SSL/TLS is used
#disable_plaintext_auth = no
# Verify client certificate
#ssl_verify_client = no
# Client verify file and/or path
#ssl_verify_file =
#ssl_verify_path =
#tls_min_proto = tls1.2

# Connection to the storage server.
# Please refer to the administrator manual or manpage why HTTP is used rather than the UNIX socket.
server_socket = http://localhost:236/
# Bypass authentification when connecting as an administrator to the UNIX socket.
bypass_auth = yes

# Whether to show the hostname in the logon greeting to clients.
server_hostname_greeting = no
# Override own DNS name for presentation in the protocol greeting line.
#server_hostname =

#log_method = auto
# Loglevel (0(none), 1(crit), 2(err), 3(warn), 4(notice), 5(info), 6(debug))
log_level = 3
log_file = -
log_timestamp = yes

# Only mail folder for IMAP or all subfolders (calendar, contacts, tasks, etc. too)
imap_only_mailfolders = yes
# Show Public folders for IMAP
imap_public_folders = yes
# The maximum size of an email that can be uploaded to the gateway
imap_max_messagesize = 128M
```

**Comment by mlan** [comment] 2020-11-03 12:08
Duplicate of #3

**Comment by mlan** [comment] 2020-11-04 20:31
Yes, some settings need to be changed to make kopano-gateway useful. I will release a new version of the repo addressing this shortly.

BTW. You can see the current configuration by running

```sh
kopano-gateway --dump-config
```
Moreover, there are example cfg files within the container. For example; `/usr/share/doc/kopano/example-config/gateway.cfg`

**Comment by osnet** [comment] 2020-11-04 20:39
nice work man, 
do you plan to make some settings available  via  .env ?
things like  message size, cert files  and bla ?

just to be clear,  i get my certs via certbot  on one of my proxys,  they are then scp / rsynced to the docker hosts... 
the built in certbot stuff doesnt work for me : )

_sry 4 eventually harsh and bad expression : )_

**Comment by mlan** [comment] 2020-11-09 16:36
Fixed in 2acaf05d930667422ef88030c00f9d07d8f3005d. See [Enabling IMAP, POP3 and ICAL](https://github.com/mlan/docker-kopano#enabling-imap-pop3-and-ical). Mark as closed.

**Closed by mlan** 2020-11-09 16:36 UTC
Labels: bug

**Comment by mlan** [comment] 2020-11-09 21:06
@osnet 

I see you mention "message size", so I was thinking is this that you are thinking about: [`MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT-25600000}`](https://github.com/mlan/docker-postfix-amavis/blob/4822bce0c3775c51ddb73ff4177773fe6d44e17e/demo/docker-compose.yml#L52)?

Concerning "certbot" and "cert files", perhaps [Let’s Encrypt LTS certificates using Traefik](https://github.com/mlan/docker-postfix-amavis#lets-encrypt-lts-certificates-using-traefik) is relevant?

**Comment by osnet** [comment] 2020-11-09 22:00
mmh maybe some guys are using traefik 

i use an nginx with lua framework aka openresty for keycloak within vhosts 

openresty on the proxies are on dmz and getting certbot ssl 
i pull the pem files per rsync to the docker hosts if needed 
so i have to tell the container where i put them

**Comment by mlan** [comment] 2020-11-16 13:40
@osnet in 162e9ca256f0bb93839889dd5438c0e780cac3e7 support for adding SSL certificates was introduced, see [Enabling IMAPS, POP3S and ICALS](https://github.com/mlan/docker-kopano#enabling-imaps-pop3s-and-icals).
